# Mutation testing configuration for mutmut
# https://mutmut.readthedocs.io/

[mutmut]
# Paths to mutate
paths_to_mutate = paper_games/,card_games/

# Paths to exclude from mutation
paths_to_exclude = 
    */tests/*,
    */demo*.py,
    */gui.py,
    */__main__.py,
    */__init__.py

# Test runner command
runner = python -m pytest tests/ -x --assert=plain -o log_cli=false

# Backup directory
backup = true

# Use coverage data to only mutate covered lines
use_coverage = true

# Test time multiplier (mutations taking longer than this are killed)
test_time_multiplier = 2.0

# Test time base (minimum time to wait)
test_time_base = 0.0

# Number of parallel mutation testing processes
# Set to 0 for auto-detection
swallow_output = true

# Cache directory
dict_synonyms = "Struct", "NamedStruct", "NamedTuple", "namedtuple"
