# CI workflow
# Combined continuous integration check that runs all quality gates

name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  QT_QPA_PLATFORM: offscreen
  XDG_RUNTIME_DIR: /tmp/qt-runtime

jobs:
  validate-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Prepare workflow validation cache directory
        run: mkdir -p .github/workflows/.workflow-validation-cache

      - name: Check workflow validation cache
        id: workflow-cache
        uses: actions/cache@v4
        with:
          path: .github/workflows/.workflow-validation-cache
          key: workflow-validation-${{ hashFiles('.github/workflows/*.yml', '.github/workflows/events/**') }}

      - name: Set up Python
        if: steps.workflow-cache.outputs.cache-hit != 'true'
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install workflow validation dependencies
        if: steps.workflow-cache.outputs.cache-hit != 'true'
        run: pip install PyYAML

      - name: Run workflow validator
        id: run-workflow-validator
        if: steps.workflow-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          set -o pipefail
          python scripts/validate_workflows.py | tee workflow-validation.log

      - name: Publish workflow validation summary
        if: steps.workflow-cache.outputs.cache-hit != 'true' && (success() || failure())
        run: |
          {
            echo "### Workflow Validation";
            echo;
            if [ -f workflow-validation.log ]; then
              cat workflow-validation.log;
            else
              echo "Workflow validation log not found. The validator step may have been skipped or failed before producing output.";
            fi;
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Workflow validation skipped
        if: steps.workflow-cache.outputs.cache-hit == 'true'
        run: |
          {
            echo "### Workflow Validation";
            echo;
            echo "Workflow files unchanged since the last successful validation. Skipping validation run.";
          } >> "$GITHUB_STEP_SUMMARY"

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package with development dependencies
        run: pip install -e ".[dev]"

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk libgl1 libxkbcommon-x11-0
          sudo rm -rf /tmp/qt-runtime
          mkdir -p /tmp/qt-runtime
          chmod 700 /tmp/qt-runtime

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package with development dependencies
        run: pip install -e ".[dev]"

      - name: Run tests with coverage (skip performance benchmarks)
        run:
          python -m pytest tests/ -v -m "not performance" --cov=paper_games --cov=card_games --cov-report=xml
          --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: matrix.python-version == '3.12'
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
