# Coverage workflow
# Generates detailed coverage reports and uploads to Codecov

name: Coverage

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests with coverage
        run: |
          python -m pytest tests/ -v \
            --cov=paper_games \
            --cov=card_games \
            --cov-report=xml \
            --cov-report=html \
            --cov-report=term-missing \
            -m "not slow"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
          verbose: true

      - name: Archive coverage HTML report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 30

      - name: Coverage summary
        run: |
          echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          python -m pytest tests/ --cov=paper_games --cov=card_games --cov-report=term-missing -m "not slow" 2>&1 | tail -50 >> $GITHUB_STEP_SUMMARY
