name: Docs Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  build-docs:
    name: Build Sphinx Documentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "docs/requirements.txt"

      - name: Install documentation requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build HTML documentation
        run: sphinx-build -b html docs/source docs/build/html

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html-${{ matrix.python-version }}
          path: docs/build/html

      - name: Publish summary
        if: ${{ success() || failure() }}
        run: |
          {
            echo "### Documentation build (${{ matrix.python-version }})";
            if [ "${{ job.status }}" = "success" ]; then
              echo "✅ Sphinx build completed successfully.";
            else
              echo "❌ Sphinx build failed.";
            fi;
          } >> "$GITHUB_STEP_SUMMARY"
