# Format and Lint Auto-fix workflow
# This workflow is for local development - it auto-formats code
# on workflow_dispatch. For CI checks, use the 'lint.yml' workflow instead

name: Format and Lint (Auto-fix)

on:
  workflow_dispatch: # Manual trigger only

permissions:
  contents: write

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package with development dependencies
        run: pip install -e ".[dev]"

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "style: auto-format code"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
