name: Format and Lint

on:
  push:
  pull_request:

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install black mdformat ruff

      - name: Run formatters
        run: |
          black .
          mdformat .

      - name: Fix lint warnings
        run: |
          ruff check . --fix
          mdformat . --check
