# Lint and format check workflow
# Verifies code style compliance without making changes

name: Lint

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black mdformat ruff

      - name: Check formatting with Black
        run: |
          black --check .

      - name: Check markdown formatting
        run: |
          mdformat --check .

      - name: Run Ruff linter
        run: |
          ruff check .
