# Lint and format check workflow
# Verifies code style compliance without making changes

name: Lint

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: |
            requirements-dev.txt

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install linting tools
        run: pip install -r requirements-dev.txt

      - name: Check formatting with Black
        run: black --check .

      - name: Check markdown formatting
        run: mdformat --check .

      - name: Run Ruff linter
        run: ruff check .
