# Manual coverage workflow
# Generates an HTML and XML coverage report on demand

name: "Manual Coverage Report"

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.12"
        required: false
      include-slow-tests:
        description: "Include tests marked as slow"
        type: boolean
        default: false
      upload-to-codecov:
        description: "Upload coverage report to Codecov"
        type: boolean
        default: true

permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests with coverage
        env:
          INCLUDE_SLOW: ${{ inputs.include-slow-tests }}
        run: |
          set -o errexit
          set -o pipefail

          MARK_EXPR='not slow'
          if [ "${INCLUDE_SLOW}" = "true" ]; then
            MARK_EXPR=''
          fi

          python -m pytest tests/ -v \
            --cov=paper_games \
            --cov=card_games \
            --cov-report=xml \
            --cov-report=html \
            --cov-report=term-missing \
            ${MARK_EXPR:+-m "${MARK_EXPR}"}

      - name: Upload coverage to Codecov
        if: inputs.upload-to-codecov == true
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
          verbose: true

      - name: Archive coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: manual-coverage-html
          path: htmlcov/
          retention-days: 14

      - name: Coverage summary
        run: |
          echo "## Manual Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          tail -n 200 coverage.xml >> $GITHUB_STEP_SUMMARY
