# Mutation Testing workflow
# Validates test quality by introducing mutations and checking if tests catch them
# This workflow is run manually or on a schedule to avoid long CI times

name: Mutation Testing

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday at midnight

permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  QT_QPA_PLATFORM: offscreen
  XDG_RUNTIME_DIR: /tmp/qt-runtime

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  mutation-test:
    runs-on: ubuntu-latest
    timeout-minutes: 120 # Mutation testing can take a long time

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk libgl1 libxkbcommon-x11-0
          sudo rm -rf /tmp/qt-runtime
          mkdir -p /tmp/qt-runtime
          chmod 700 /tmp/qt-runtime

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package with development dependencies
        run: pip install -e ".[dev]"

      - name: Run mutation testing
        id: mutmut-run
        continue-on-error: true
        run: |
          set +e
          mutmut run
          status=$?
          echo "status=$status" >> "$GITHUB_OUTPUT"
          exit $status

      - name: Generate mutation report
        run: |
          mutmut results
          mutmut html || true

      - name: Upload mutation report
        uses: actions/upload-artifact@v4
        with:
          name: mutation-report
          path: html/
          retention-days: 30

      - name: Mutation testing summary
        if: always()
        run: |
          {
            echo "## Mutation Testing Results";
            echo;
            mutmut results || echo "Mutation testing report generated";
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Highlight surviving mutants
        if: steps.mutmut-run.outcome == 'failure'
        run: echo "::warning::Mutmut detected surviving mutants. Review the summary above for details."
